const data = {
    products: [
        {
            _id: "1",
            name: "Nike Slim Shirt",
            category: "Shirts",
            image: "../images/p1.jpg",
            price: 1200,
            countInStock: 10,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "high quality products",
        },
        {
            _id: "2",
            name: "Adidas Fit Shirt",
            category: "Shirts",
            image: "../images/p2.jpg",
            price: 2600,
            countInStock: 20,
            brand: "Adidas",
            rating: 4.5,
            numReviews: 100,
            description: "high quality products",
        },
        {
            _id: "3",
            name: "Lacoste Free Shirt",
            category: "Shirts",
            image: "../images/p3.jpg",
            price: 2200,
            countInStock: 100,
            brand: "Lacoste",
            rating: 4.5,
            numReviews: 17,
            description: "high quality products",
        },
        {
            _id: "4",
            name: "Nike Slim Pants",
            category: "Pants",
            image: "../images/p4.jpg",
            price: 1800,
            countInStock: 50,
            brand: "Nike",
            rating: 4.5,
            numReviews: 20,
            description: "high quality products",
        },
        {
            _id: "5",
            name: "Puma Slim Pants",
            category: "Pants",
            image: "../images/p5.jpg",
            price: 1000,
            countInStock: 10,
            brand: "Puma",
            rating: 4.5,
            numReviews: 11,
            description: "high quality products",
        },
        {
            _id: "6",
            name: "Adidas Fit Pant",
            category: "Pants",
            image: "../images/p6.jpg",
            price: 2500,
            countInStock: 60,
            brand: "Adidas",
            rating: 4.5,
            numReviews: 10,
            description: "high quality products",
        },
        {
            _id: "7",
            name: "Adidas Fit Shirt",
            category: "Shirts",
            image: "../images/p2.jpg",
            price: 2600,
            countInStock: 10,
            brand: "Adidas",
            rating: 4.5,
            numReviews: 100,
            description: "high quality products",
        },
        {
            _id: "8",
            name: "Adidas Fit Shirt",
            category: "Shirts",
            image: "../images/p2.jpg",
            price: 2600,
            countInStock: 30,
            brand: "Adidas",
            rating: 4.5,
            numReviews: 100,
            description: "high quality products",
        },
    ],
};

export default data;
